# RENAME FILE TO 'config.yml'
bot:
  token: MTI0NTQyODk2MjQxMTE1MTQwMQ.GEYZzK.NowlfV0OTbyHBiq6N-elhQ2LR7kirkYBaFn4ik
  owner_ids:
    - 1245426022623613080
    - 155149108183695360
  prefix: $
  default_bet: 100
  bonus_multiplier: 5 # bonus = default_bet * multiplier
  bonus_cooldown: 12 # Bonus every x hours
